In [121]:
import cv2
from imutils import paths
import numpy as np
from scipy.spatial import distance as dis

In [122]:
image1=cv2.imread(r'C:\Users\arpit14276\Desktop\facerecognization\dogs\th7RRHY09L.jpg')

In [123]:
image2=cv2.imread(r'C:\Users\arpit14276\Desktop\facerecognization\horse\Tarpan-myth-152.jpg')

In [124]:
##check 
i=cv2.split(image)
i[0].sum()
image.shape

(206, 309, 3)

In [125]:
## function to calculate the distance 
def colordistance(image1,image2):
    dis1=cv2.meanStdDev(image1)
    dis2=cv2.meanStdDev(image2)
    add=[]
    for i,j in zip(dis1,dis2):
        add.append((i-j)**2)
    return np.sqrt(sum(sum(add)))
colordistance(image1,image2)

array([50.20801859])

In [126]:
## function using libraries

imagepath=sorted(list(paths.list_images(r'C:\Users\arpit14276\Desktop\facerecognization\horse')))
index={}
for images in imagepath:
    image=cv2.imread(images)
    filename=images
    (means,stds)=cv2.meanStdDev(image)
    features=np.concatenate([means,stds]).flatten()
    index[filename]=features


In [127]:
query=cv2.imread(r'C:\Users\arpit14276\Desktop\facerecognization\horse\Tarpan-myth-152.jpg')

In [128]:
keys=sorted(index.keys())

In [129]:
for i,j in enumerate(keys):
    if j==r'C:\Users\arpit14276\Desktop\facerecognization\horse\Tarpan-myth-152.jpg':
        continue
    im=cv2.imread(j)
    d=dis.euclidean(index[r'C:\Users\arpit14276\Desktop\facerecognization\horse\Tarpan-myth-152.jpg'],index[j])
    cv2.putText(im,"%.2f" % (d),(10,30),cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 255, 0), 2)
    cv2.imshow(j,im)
cv2.imshow('query',query)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [99]:
features

array([130.04244824, 142.48868885, 133.06393942,  67.75802596,
        57.76058154,  62.7182011 ])

In [100]:
####quiz ###

In [118]:
quiz=cv2.imread(r'C:\Users\arpit14276\Desktop\pyimagesearch\raptors_02.png')

In [119]:
(i,j)=cv2.meanStdDev(quiz)
features2=np.concatenate([i,j]).flatten()

In [117]:
features1

array([33.40508234, 29.97264203, 39.20540541, 27.05237628, 23.14341739,
       24.45663121])

In [120]:
dis.euclidean(features1,features2)

5.968268349855276