In [2]:
import cv2
import numpy as np

### Translational  (chnage of cordinates )

In [2]:
# NOTE: Translating (shifting) an image is given by a NumPy matrix in
# the form:
#	[[1, 0, shiftX], [0, 1, shiftY]]
# You simply need to specify how many pixels you want to shift the image
# in the X and Y direction -- let's translate the image 25 pixels to the
# right and 50 pixels down

#NOTE:  right shift is +x , down shift is +ve y

In [4]:
i=cv2.imread(r'C:\Users\arpit14276\Desktop\pyimagesearch\splitting_and_merging\florida_trip_small.png')

In [ ]:
## from cv2 library 
M = np.float32([[1, 0, 25], [0, 1, 50]])
shifted = cv2.warpAffine(x, M, (x.shape[1], x.shape[0]))
cv2.imshow("Shifted Down and Right", shifted)
cv2.waitKey(0)

In [4]:
## manually created Translational function 
def shift(image,x_shift,y_shift):
    x=image.shape[1]
    y=image.shape[0]
    black=np.zeros((y,x,3),dtype='uint8')
    print (x_shift,y_shift)
    if x_shift>0 and y_shift<0:
        print (1)
        black[abs(y_shift):,x_shift:]=image[0:y+y_shift,0:x-x_shift]
    elif x_shift<0 and y_shift<0:
        print (2)
        black[abs(y_shift):,0:x+x_shift]=image[0:y+y_shift,abs(x_shift):]
    elif x_shift<0 and y_shift>0:
        print (3)
        black[:y-y_shift,:x+x_shift]=image[y_shift:,0:x+x_shift]
    elif x_shift>0 and y_shift>0: 
        print (4)
        black[:y-y_shift,x_shift:]=image[y_shift:,0:x-x_shift]
    else :
        print (5)
    cv2.imshow('shift',black)
    cv2.waitKey(0)
    return black
   
    
        

In [5]:
t=shift(i,25,50)


25 50
4


In [ ]:
### rotation


In [ ]:
(h,w)=i.shape[:2]

In [ ]:
(h,w)=i.shape[:2](cw,ch)=(w/2,h/2)

In [ ]:
M=cv2.getRotationMatrix2D((cw -50,ch-50),45,1)

In [ ]:
r=cv2.warpAffine(i,M,(w,h))
cv2.imshow('rotate by 45*',r)
cv2.waitKey(0)

In [16]:
(h, w) = i.shape[:2]
(cw, ch) = (w / 2, h / 2)
 
# rotate our image by 45 degrees
M = cv2.getRotationMatrix2D((cw, ch), 110, 1.0)
rotated = cv2.warpAffine(i, M, (w, h))
#cv2.imshow("Rotated by 45 Degrees", rotated)
#cv2.waitKey(0)
rotated[136,312]

array([128, 131, 170], dtype=uint8)

In [4]:
import math
def rotate(i,angle):
    
    x=i.shape[1]
    y=i.shape[0]
    black=np.zeros((y,x,3),dtype='uint8')
    angle=angle*(22/7*180)
    rotation=[]
    for k in range(x):
        for j in range(y):
            rotation=[round(k*math.cos(angle)-j*math.sin(angle)),round(k*math.sin(angle)+j*math.cos(angle))]
            #print (rotation)
            if rotation[0]==0 or rotation[1]==0:
                rotation[0]=0
                rotation[1]=0
           
            try:
                
                black[rotation]=i[k,j]
            except:
                pass
    cv2.imshow('ro',black)
    cv2.waitKey(0)
    return black

In [8]:
rotate(i,45)

array([[[  9,  49,  33],
        [  9,  49,  33],
        [  9,  49,  33],
        ...,
        [  9,  49,  33],
        [  9,  49,  33],
        [  9,  49,  33]],

       [[  4,  16,  10],
        [  4,  16,  10],
        [  4,  16,  10],
        ...,
        [  4,  16,  10],
        [  4,  16,  10],
        [  4,  16,  10]],

       [[  5,  17,   9],
        [  5,  17,   9],
        [  5,  17,   9],
        ...,
        [  5,  17,   9],
        [  5,  17,   9],
        [  5,  17,   9]],

       ...,

       [[159, 149, 175],
        [159, 149, 175],
        [159, 149, 175],
        ...,
        [159, 149, 175],
        [159, 149, 175],
        [159, 149, 175]],

       [[120, 104, 128],
        [120, 104, 128],
        [120, 104, 128],
        ...,
        [120, 104, 128],
        [120, 104, 128],
        [120, 104, 128]],

       [[177, 166, 135],
        [177, 166, 135],
        [177, 166, 135],
        ...,
        [177, 166, 135],
        [177, 166, 135],
        [177, 166, 135]]

In [ ]:
### Resize (interpolation )
# we need to keep in mind aspect ratio so the image does not look skewed
# or distorted -- therefore, we calculate the ratio of the new image to
# the old image.

In [ ]:
#aspect ration =width /height of an image
# width=image.shape[1]--> columns
# height=image.shape[0]==> rows
#while resizing the image aspect ration must be preserved 
# if we want to increase the width by 150 , so new height =[150/old height(image.shae[1])]old width(image.shape[0])
# interpolation methods available in cv2 , INTER_AREA,INTER_LINEAR,INTER_NEAREST,INTER_CUBIC,INTER_LANCZ0S4

In [33]:
r=600/i.shape[1]

In [40]:
new_dim=(600,int(r*i.shape[0]))

In [41]:
resized=cv2.resize(i,new_dim,interpolation=cv2.INTER_CUBIC)
#cv2.imshow('resized',resized)
#cv2.waitKey(0)

In [42]:
resized[367,170]

array([27, 22, 21], dtype=uint8)

In [27]:
i.shape

(450, 600, 3)

In [43]:
######## FLIPPING ############## i.e mirror image

In [56]:
#1 for horizontal , 0 or vertical , -1 for both
flipped=cv2.flip(i,1)

cv2.imshow('flipped',flipped)
cv2.waitKey(0)


48

In [58]:
## flipped then rotatelipped=cv2.flip(i,1)
flipped=cv2.flip(i,1)
(h,w)=flipped.shape[:2]
(cw,ch)=(w/2,h/2)
M=cv2.getRotationMatrix2D((cw,ch),45,1)
r=cv2.warpAffine(flipped,M,(w,h))
cv2.imshow('rotate by 45*',r)
cv2.waitKey(0)

In [52]:
flipped[259,235]

array([183, 186, 177], dtype=uint8)

In [60]:
###### CROPPING

In [61]:
# Generally e use this when we want to extract region of interest from the give image (ROI)
# crop the area which is ROI and print it , we canuse it in machine learning 

In [68]:
cv2.imshow('test',i[90:450, 0:290])
cv2.waitKey(0)

48

In [69]:
### IMAGE Airthmetic ###

In [70]:
'''addition and subtraction of an image is same as add and subtraction operation of an matrix , only difference is pixel value only ranges between 0-255
so when ever we add two images we need to clip it to neareast value  either 0 or 255
when we add uint8 values and if it exceed from 255 then in numpy  we clip it on the basis of modulus function 
255+10=265 , after operation 265%255= 10'''

'addition and subtraction of an image is same as add and subtraction operation of an matrix , only difference is pixel value only ranges between 0-255\nso when ever we add two images we need to clip it to neareast value  either 0 or 255'

In [72]:
np.uint8([200]).shape

(1,)

In [77]:
m=np.ones(i.shape,dtype='uint8')*100

In [78]:
sub=cv2.subtract(i,m) #for addition cv2.add()
cv2.imshow('subtract:',sub)
cv2.waitKey(0)

111

In [86]:
-250%255

5

In [88]:
#### BITwise operations #############
# and or zor not
# generally use when ROI is not rectangular or circle (polygon,etc etc)

In [3]:
rect=np.zeros((300,300),dtype='uint8')

In [5]:
cv2.rectangle(rect,(75,25),(275,275),255,-1)
cv2.imshow('rect',rect)
cv2.waitKey(0)

48

In [7]:
cir=np.zeros((300,300),dtype='uint8')
cv2.circle(cir,(150,150),150,255,-1)
cv2.imshow('circle',cir)
cv2.waitKey(0)

48

In [8]:
# or (if botth is 0 then only 0 else 1 )
# and (both need to be 1 to make it 1)
# not (inverse)
# xor (true if and only if one of the two pixels is greater than zero, but not both.)

In [9]:
#XOR
bit=cv2.bitwise_xor(rect,cir)
cv2.imshow('xor',bit)
cv2.waitKey(0)

55

In [10]:
#AND
bit=cv2.bitwise_and(rect,cir)
cv2.imshow('and',bit)
cv2.waitKey(0)

32

In [11]:
##### MASKING  ########

In [15]:
print (i.shape)
mask=np.zeros(i.shape[:2],dtype='uint8')
cv2.rectangle(mask,(0,90),(220,250),255,-1)
cv2.imshow('rect',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

(188, 250, 3)


In [16]:
masked=cv2.bitwise_and(i,i,mask=mask)
cv2.imshow('masked',masked)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
100//10


10

In [15]:
#### SPLITTING and MERGIG of Channels ####

In [38]:
b=i[:,:,0]
g=i[:,:,1]
r=i[:,:,2]

In [26]:
cv2.imshow("Red", r)
cv2.imshow("Green", g)
cv2.imshow("Blue", b)
cv2.waitKey(0)

32

In [34]:
#function
(b,g,r)=cv2.split(i)
cv2.imshow("Red", r)
cv2.imshow("Green", g)
cv2.imshow("Blue", b)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
#merge
merged=cv2.merge([b,g,r])
cv2.imshow('merge',merged)
cv2.waitKey(0)

32

In [36]:
# visualizing as per color
zeros=np.ones(i.shape[:2],dtype='uint8')
cv2.imshow('red',cv2.merge([zeros,zeros,r]))
cv2.imshow('green',cv2.merge([zeros,r,zeros]))
cv2.imshow('blue',cv2.merge([r,zeros,zeros]))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
g[5,80]

249